//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFoodManagmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMenuItem()
        {
            this.tblRestaurants = new HashSet<tblRestaurant>();
        }
    
        public int fooditemid { get; set; }
        public string foodname { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> isavailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRestaurant> tblRestaurants { get; set; }
    }
}
