//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFoodManagmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRestaurant
    {
        public int restaurantID { get; set; }
        public string restaurantname { get; set; }
        public Nullable<int> fooditemid { get; set; }
    
        public virtual tblMenuItem tblMenuItem { get; set; }
    }
}
